version: "3.8"
services:
  db:
    image: neo4j:enterprise
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - data:/data
      - logs:/logs
#      - import:/import
#      - plugins:/plugins
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_uuid_enabled=true
    env_file: .env
    restart: always

volumes:
  data: {}
  logs: {}
#  import: {}
#  plugins: {}