spring:
  application:
    name: wiki-tracker-api
  data:
    neo4j:
      uri: neo4j://localhost:7687
      username: neo4j
      password: test
      use-native-types: true
  datasource:
    url: jdbc:neo4j:bolt://localhost
    username: neo4j
    password: test
    driver-class-name: org.neo4j.jdbc.bolt.BoltDriver
  profiles:
    active: dev

#logging:
#  level:
#    root: debug

server:
  port: 8000
  error:
    include-message: on_param
