spring:
  application:
    name: wiki-tracker-api
  data:
    neo4j:
      uri: neo4j://localhost:7687
      username: neo4j
      password: test
  logging:
    level:
      root: DEBUG

server:
  port: 8000